# Generated by Django 3.2.9 on 2021-11-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empapp', '0002_auto_20211114_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_terms', to='empapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='BonusTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_schema', models.CharField(choices=[('flat', 'Фиксированная сумма'), ('percent', 'Процент от оклада'), ('complex', 'Отдельная схема премирования')], max_length=10)),
                ('bonus_period', models.CharField(choices=[('annual', 'Год'), ('semiannual', 'Полугодие'), ('quarterly', 'Квартал'), ('monthly', 'Месяц'), ('other', 'Другое')], max_length=10)),
                ('bonus_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_terms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonus', to='termsapp.salaryterms')),
            ],
        ),
    ]
