# Generated by Django 3.2.9 on 2021-11-15 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('termsapp', '0003_alter_bonusterms_salary_terms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusterms',
            options={'verbose_name': 'условия премии', 'verbose_name_plural': 'условия премий'},
        ),
        migrations.AlterModelOptions(
            name='salaryterms',
            options={'verbose_name': 'оклад', 'verbose_name_plural': 'оклады'},
        ),
        migrations.AddField(
            model_name='bonusterms',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonusterms',
            name='is_actual',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonusterms',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salaryterms',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryterms',
            name='is_actual',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryterms',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
