# Generated by Django 3.2.9 on 2021-11-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termsapp', '0004_auto_20211115_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusterms',
            name='is_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salaryterms',
            name='is_actual',
            field=models.IntegerField(default=0),
        ),
    ]
