# Generated by Django 3.2.9 on 2021-11-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_auto_20211114_1508'),
        ('changeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeechange',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='empapp.employee'),
        ),
        migrations.AlterField(
            model_name='newdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_changes', to='empapp.department'),
        ),
        migrations.AlterField(
            model_name='newjobtitle',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_changes', to='empapp.jobtitle'),
        ),
        migrations.AlterField(
            model_name='newstaffposition',
            name='staff_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_changes', to='empapp.staffposition'),
        ),
    ]
