# Generated by Django 3.2.9 on 2021-11-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeapp', '0002_auto_20211115_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuschange',
            options={'verbose_name': 'изменение условий премии', 'verbose_name_plural': 'изменения условий премии'},
        ),
        migrations.AlterModelOptions(
            name='changegroup',
            options={'verbose_name': 'группа изменений', 'verbose_name_plural': 'группы изменений'},
        ),
        migrations.AlterModelOptions(
            name='departmentchange',
            options={'verbose_name': 'изменение подразделения', 'verbose_name_plural': 'изменения подразделения'},
        ),
        migrations.AlterModelOptions(
            name='employeechange',
            options={'verbose_name': 'изменение условий сотрудника', 'verbose_name_plural': 'изменения условий сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='jobtitlechange',
            options={'verbose_name': 'изменения должности', 'verbose_name_plural': 'изменения должности'},
        ),
        migrations.AlterModelOptions(
            name='managerchange',
            options={'verbose_name': 'изменение руководителя', 'verbose_name_plural': 'изменения руководителя'},
        ),
        migrations.AlterModelOptions(
            name='newdepartment',
            options={'verbose_name': 'новое подразделение', 'verbose_name_plural': 'новые подразделения'},
        ),
        migrations.AlterModelOptions(
            name='newjobtitle',
            options={'verbose_name': 'новая должность', 'verbose_name_plural': 'новые должности'},
        ),
        migrations.AlterModelOptions(
            name='newstaffposition',
            options={'verbose_name': 'новые штатные позиции', 'verbose_name_plural': 'новые штатные позиции'},
        ),
        migrations.AlterModelOptions(
            name='otherchange',
            options={'verbose_name': 'изменения других условий', 'verbose_name_plural': 'изменения других условий'},
        ),
        migrations.AlterModelOptions(
            name='salarychange',
            options={'verbose_name': 'изменение оклада', 'verbose_name_plural': 'изменения оклада'},
        ),
    ]
