# Generated by Django 3.2.9 on 2021-11-15 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empapp', '0004_auto_20211115_1503'),
        ('changeapp', '0003_auto_20211115_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'изменение',
                'verbose_name_plural': 'изменения',
                'ordering': ['-updated_date'],
            },
        ),
        migrations.RemoveField(
            model_name='departmentchange',
            name='employee_change',
        ),
        migrations.RemoveField(
            model_name='departmentchange',
            name='new_department',
        ),
        migrations.RemoveField(
            model_name='departmentchange',
            name='old_department',
        ),
        migrations.RemoveField(
            model_name='employeechange',
            name='change_group',
        ),
        migrations.RemoveField(
            model_name='employeechange',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='jobtitlechange',
            name='employee_change',
        ),
        migrations.RemoveField(
            model_name='jobtitlechange',
            name='new_job_title',
        ),
        migrations.RemoveField(
            model_name='jobtitlechange',
            name='old_job_title',
        ),
        migrations.RemoveField(
            model_name='managerchange',
            name='employee_change',
        ),
        migrations.RemoveField(
            model_name='managerchange',
            name='new_manager',
        ),
        migrations.RemoveField(
            model_name='managerchange',
            name='old_manager',
        ),
        migrations.RemoveField(
            model_name='newdepartment',
            name='change_group',
        ),
        migrations.RemoveField(
            model_name='newdepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='newjobtitle',
            name='change_group',
        ),
        migrations.RemoveField(
            model_name='newjobtitle',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='newstaffposition',
            name='change_group',
        ),
        migrations.RemoveField(
            model_name='newstaffposition',
            name='staff_position',
        ),
        migrations.RemoveField(
            model_name='otherchange',
            name='employee_change',
        ),
        migrations.RemoveField(
            model_name='salarychange',
            name='employee_change',
        ),
        migrations.AddField(
            model_name='changegroup',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changegroup',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('forfeited', 'Отменено'), ('processing', 'Согласовывается'), ('approved', 'Согласовано'), ('executed', 'Выполнено')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='changegroup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BonusChange',
        ),
        migrations.DeleteModel(
            name='DepartmentChange',
        ),
        migrations.DeleteModel(
            name='EmployeeChange',
        ),
        migrations.DeleteModel(
            name='JobTitleChange',
        ),
        migrations.DeleteModel(
            name='ManagerChange',
        ),
        migrations.DeleteModel(
            name='NewDepartment',
        ),
        migrations.DeleteModel(
            name='NewJobTitle',
        ),
        migrations.DeleteModel(
            name='NewStaffPosition',
        ),
        migrations.DeleteModel(
            name='OtherChange',
        ),
        migrations.DeleteModel(
            name='SalaryChange',
        ),
        migrations.AddField(
            model_name='changes',
            name='change_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_departments', to='changeapp.changegroup'),
        ),
        migrations.AddField(
            model_name='changes',
            name='new_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='switch_to_changes', to='empapp.staffposition'),
        ),
        migrations.AddField(
            model_name='changes',
            name='old_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='switch_from_changes', to='empapp.staffposition'),
        ),
    ]
