# Generated by Django 3.2.9 on 2021-11-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('guid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('short_title', models.CharField(max_length=30)),
                ('group_name', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('guid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='person_photos')),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'М'), ('W', 'Ж')], max_length=1)),
                ('social_hash', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=120, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('guid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('fte_count', models.DecimalField(decimal_places=2, max_digits=5)),
                ('approved_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subordinates', to='empapp.staffposition')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('guid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hire_date', models.DateField()),
                ('exit_date', models.DateField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empapp.person')),
                ('staff_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empapp.staffposition')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('guid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empapp.organization')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subdepartments', to='empapp.department')),
            ],
        ),
    ]
