# Generated by Django 3.2.9 on 2021-11-14 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('guid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=150)),
                ('short_title', models.CharField(max_length=30)),
                ('group_name', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, upload_to='person_photos')),
                ('birth_date', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'М'), ('W', 'Ж')], max_length=1)),
                ('social_hash', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=120, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=150)),
                ('fte_count', models.DecimalField(decimal_places=2, max_digits=5)),
                ('approved_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empapp.department')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empapp.jobtitle')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subordinates', to='empapp.staffposition')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('is_vacancy', models.IntegerField(default=0)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('is_long_absence', models.IntegerField(default=0)),
                ('long_absence_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vacancy_approved_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empapp.person')),
                ('staff_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='empapp.staffposition')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empapp.organization'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subdepartments', to='empapp.department'),
        ),
    ]
