# Generated by Django 3.2.9 on 2021-11-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('staff_position__department', 'id')},
        ),
        migrations.AlterField(
            model_name='employee',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empapp.person'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vacancy_approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
