# Generated by Django 3.2.9 on 2021-11-13 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0003_auto_20211113_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('guid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='staffposition',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empapp.department'),
        ),
        migrations.AlterField(
            model_name='staffposition',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subordinates', to='empapp.staffposition'),
        ),
        migrations.AddField(
            model_name='staffposition',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empapp.jobtitle'),
        ),
    ]
