# Generated by Django 3.2.9 on 2021-11-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0003_auto_20211115_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='is_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='staffposition',
            name='is_actual',
            field=models.IntegerField(default=0),
        ),
    ]
