# Generated by Django 3.2.9 on 2021-11-14 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0005_auto_20211113_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_long_absence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='long_absence_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='staff_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='empapp.staffposition'),
        ),
    ]
