# Generated by Django 3.2.9 on 2021-11-14 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0007_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='vacancy_approved_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empapp.person'),
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
