# Generated by Django 3.2.9 on 2021-11-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0008_auto_20211114_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_vacancy',
            field=models.IntegerField(default=0),
        ),
    ]
